### ISSUE TITLE
Semantic search results sort order

### ISSUE THREAD

**Issue by klyap** [glovguy/obsidian-gpt-zettelkasten#2]
Right now, the results in the modal are listed with lowest similarity score first. Can you reverse this so that the highest scoring ones come up first?

I see that there's already sorting done so not sure why mine is showing up reversed.
https://github.com/glovguy/obsidian-gpt-zettelkasten/blob/main/src/vector_storage.ts#L68

I'm using v1.1.1 installed via Obsidian community plugins

**Comment by glovguy** [comment]
Thanks for raising this issue.

I think I see what the issue is. Let me confirm and send up a fix.

**Comment by glovguy** [comment]
The issue was that the incorrect `main.js` file got included in the `1.1.1` release bundle. The `main.js` that was attached did not match the source code for the `1.1.1` tag.

I've just updated the release, so anyone downloading it anew will get the correct file. I'll push a patch version with some whitespace changes to ensure that any systems with the `1.1.1` tag know to update.

Thanks again for raising!

**Comment by glovguy** [comment]
I published a version `1.1.2` that fixes this. I was able to download the update and confirm the sort order is correct. Will be writing a script to automate updates to this repo to avoid issues like this in the future.

If after downloading the update and then restarting Obsidian you're still seeing an issue, please reopen this issue. Thanks!

**Comment by klyap** [comment]
Thanks! I just updated to 1.1.2 and that worked!
